### PR TITLE
added option to disable dns in wireguard conf

### PR DESCRIPTION
**Pull request by gchamon**
to:
cc: @subspacecommunity/subspace-maintainers
related to:
resolves:

## Background

To avoid wrong regional DNS resolution, which would cause international users to try to connect to the wrong servers when using the DNS provided by subspace, an option should exist to disable the DNS entry in wireguard conf.

### Changes

* added env var `SUBSPACE_DISABLE_DNS` which acts as a toogle and, when set, causes new config files to be created with the DNS entry ommited.
* disabling dnsmasq if the flag is set
* updating readme

## Testing

Create a new subspace instance with `SUBSPACE_DISABLE_DNS=1`, create a new config file, check if `DNS =` in wg0.conf is ommited:

```conf
[Interface]
PrivateKey = {REDACTED}
Address = 10.99.97.2/24,fd00::10:97:2/64

[Peer]
PublicKey = XIvA8kM+O9M+FGgR1SvkCv2DDrxWah+wp10tRfYAVzU=

Endpoint = {REDACTED}:51820
AllowedIPs = 0.0.0.0/0, ::/0
```

### CODE REVIEW

**Comment by agonbar** [comment]
Hi! I tested this, but I think it needs a bit more work.

Right now, the dnsmasq server is still getting launched without taking into consideration the env variable. To avoid unnecesary confusion, the DNS server should only be started if needed.

Also, adding a new var to the config, should be on the Docker-Compose Example section of the readme, or maybe we can refactor the way we explain all this vars to the users.

**Comment by gchamon** [comment]
@agonbar I think refactoring the readme to make the env vars easier to understand for the users is worth its own separate issue. I will, however update my PR with your suggestions

**Review by agonbar — APPROVED** [review]
Nice! I just tried this, it works! Sorry for the delay. Respecting the other PR, a rebase can be made and any extra feature can be introduced there.

**Comment by agonbar** [comment]
@all-contributors please add @gchamon  for code

**Pull request merged**
