### PR TITLE
Feature/totp default admin

### PR DESCRIPTION
**Pull request by agonbar**
to:
cc: @subspacecommunity/subspace-maintainers
related to: #111 
resolves: #104

## Background

NEW: This fixes a typo in the last commited change, I'll copy all the contents from the original PR

Wanted to secure the default user of subspace with TOTP. Now it is possible to turn on TOTP for the default user by visiting `/settings` and scanning the QR code with your phone (or putting the secret key into something else)

### Changes

* Configure TOTP via `/settings`
* Reset TOTP via `/settings` (only visible if TOTP is already configured)
* Can only be done by an `Admin` (This means both SAML Signed in Admin and the default Admin)

### Pics

Initial Setup of MFA
Setup MFA

Reset MFA (will then result in the above page)
reset totp

Sign in page for default admin account if TOTP has been saved
Sign in with MFA Configured

## Testing

NEW: Run from a clean file, but still needs deep testing.

Ran this locally multiple times on my Droplet in Digital Ocean (i'm using rsync to sync changes to my box and then running `docker-compose up --build -d` whenever changes are made to `go` files. For changes related static files i simply specify `--debug` in the build step for `go-bindata` and mount `web/` into the running container. `go-bindata` then reads these files live on each request :D)

### CODE REVIEW

**Comment by jack1902** [comment]
Can you fix the commits to credit myself on this?

**Comment by agonbar** [comment]
@jack1902 It should be already changed, maybe not the cleanest way, but I was on the phone. I also tested, the fix needs the email to be something, but that something can be any string, as soon as the user sets up the default account, its overwritten. I tested this branch on clean installs in my machine, in my server and in a raspberry pi and its working with clean installs, please, give it a try and tell me how it went.

**Comment by gavinelder** [comment]
Can this just be rebased onto master and PR'd from there ?

**Comment by agonbar** [comment]
It just needs to be reviewed by someone else in order to merge and close this once and for all. Or, seeing that there is a lot of traction lost, I'll wait until next week, if there is no new activity, force merge this and release a version (didn't want to but seems the only reasonable option), then move to the next PR.

**Review by jack1902 — COMMENTED** [review]
I no longer work on this project, so leaving this review to remove it from my list of PRs on Github

**Comment by gchamon** [comment]
@agonbar I applied this PR to my forked repo and have been using it without issues. Just so you know your work wasn't for nothing.

**Review by gchamon — APPROVED** [review]

**Comment by gchamon** [comment]
@agonbar @subspacecommunity/subspace-maintainers fixed the conflicts with version 1.4.1. This is ready to merge.

**Comment by agonbar** [comment]
I was waiting for someone to approve, as I'm the one credited in this PR so I was breaking the rule of 2 approvals, but, there it goes

**Pull request merged**
