### PR TITLE
Dnsmasq disabled 63

### PR DESCRIPTION
**Pull request by gilesw**
https://github.com/subspacecommunity/subspace/issues/63

### CODE REVIEW

**Comment by ishanjain28** [comment]
Hi! When can this be merged? I don't really see any blockers in merging this. 

I am running power dns on the host and don't want subspace to start it's own DNS server. Right now, It has port conflicts with power dns and won't start.

**Comment by jacksgt** [comment]
Hey, I also just ran into this. What's the rational behind running the DNS server inside the container when there is already one on the host?

Could we have some input from maintainers, please?

**Comment by agonbar** [comment]
Yes the rational behind it it's easy to explain. When we forked the project from the original authors, it was (and still is) a huge mess of bad practices. We are currently trying to rewrite most of the code to be as maintainable as possible. Maybe someone volunteers to attend the PR for the current version while the next one is being written, but it's a real pain to test changes with the current code.

Also I apologize for the slowness of development for that next version, the pandemic made a mess in the organization for this year.

**Comment by jacksgt** [comment]
> Yes the rational behind it it's easy to explain. When we forked the project from the original authors, it was (and still is) a huge mess of bad practices. We are currently trying to rewrite most of the code to be as maintainable as possible. Maybe someone volunteers to attend the PR for the current version while the next one is being written, but it's a real pain to test changes with the current code.
While this doesn't really explain why a DNS server is *necessary* inside the container, but I gather that you are open to changing this (opt-in), which is good.

@gilesw If you are still interested in this patch, could you please rebase your branch on master? Otherwise let me know, I'll do it and open a new PR.

> Also I apologize for the slowness of development for that next version, the pandemic made a mess in the organization for this year.

No worries, thanks for keeping the project going! :-)

**Comment by agonbar** [comment]
#168 Was merged, which is basically the same, many thanks anyway for all the work!

Also, sorry for the huge delay!

**Pull request closed without merging**
