### PR TITLE
Allow extending dnsmasq by providing custom configuration.

### PR DESCRIPTION
**Pull request by ThisIsQasim**
cc: @subspacecommunity/subspace-maintainers

## Background

Reason for the change

dnsmasq can be used for accomplish a wide variety of tasks. This change lets us mount dnsmasq configurations inside the subspace container to provide additional configuration to dnsmasq.

For example you could override hostnames by creating the following config file and then mounting it inside subspace.

**/opt/docker/dnsmasq/01-static-dns.conf** 
```
address=/a.example.com/172.16.0.10
address=/b.example.com/172.16.0.11
```

**docker-compose.yml**
```
   volumes:
   - /opt/docker/subspace:/data
   - /opt/docker/dnsmasq:/etc/dnsmasq.d
```

### Changes

* Include `/etc/dnsmasq.d` in dnsmasq config at `/etc/dnsmasq.conf`

## Testing

The container works as expected with additional dnsmasq configuration mounted and without.

### CODE REVIEW

**Comment by jcmontigny-fox** [comment]
This is a very welcome change ! We have that use case also. This simple change would make subspace configuration very flexible.

**Comment by gchamon** [comment]
Hey @ThisIsQasim 

Thanks for the pr and sorry for the long silence.
 Could you also expand the readme to include indications that you can provide dnsmasq by mapping the internal folder to an external one with docker?

Then I think it would make it clearer for the user. Your pr is well written but the end user won't see it.

**Comment by ThisIsQasim** [comment]
Hi @gchamon,

No need for the apologies. 
I have updated the PR with brief instructions in the readme. Does that work or should I expand it some more?

**Comment by gchamon** [comment]
@ThisIsQasim the readme overall, in my opinion (I don't speak here for the rest of the maintainers) needs some rework. This is enough to point to the fact that this config is supported like this.

I didn't have time to test it just yet, but seeing what kind of changes it introduces, the only concern would be for dnsmasq to fail with an edge case of an empty file or a file without the correct permissions. This I will test later.

**Comment by ThisIsQasim** [comment]
Sounds great. Hit me up if you want me to change something.

**Review by agonbar — APPROVED** [review]
I tested in my machine, awsome addtion! In one of my setups I was running a pi-hole just to have an easy option to serve a couple of custom domains, though the vpn instead of the public IP.

Many thanks! I'll wait for @gchamon to test this and the we can merge it once he reviews the changes.

**Comment by ThisIsQasim** [comment]
> In one of my setups I was running a pi-hole just to have an easy option to serve a couple of custom domains, though the vpn instead of the public IP.

Yup that is exactly what my use-case was.

> Many thanks! I'll wait for @gchamon to test this and the we can merge it once he reviews the changes.

Happy to be of help and thank you for maintaining this awesome project!

**Review by gchamon — APPROVED** [review]

**Comment by gchamon** [comment]
@agonbar approved

**Comment by gchamon** [comment]
@all-contributors please add @ ThisIsQasim for code

**Comment by gchamon** [comment]
@all-contributors please add @ThisIsQasim for code

**Pull request merged**
