### PR TITLE
fix ip6tables installation in dockerfile

### PR DESCRIPTION
**Pull request by sesajad**
to:
cc: @subspacecommunity/subspace-maintainers
related to:
resolves:

## Background

I was encountering 'ip6tables' not found, which was simply solved by installing the package.

### Changes

adding installation of ip6tables to Dockerfile

## Testing

I added this package to the container by extending Dockerfile locally, and solved my issue.

### CODE REVIEW

**Comment by sesajad** [comment]
solves #67

**Comment by jack1902** [comment]
@sesajad Which OS did you test this on?

**Comment by sesajad** [comment]
@jack1902 
Ubuntu 16.04.6 LTS

**Comment by gavinelder** [comment]
Thanks for this it's encompassed in https://github.com/subspacecommunity/subspace/pull/75 .

**Comment by jack1902** [comment]
As @gavinelder pointed out, this has been included in #75 so i am closing this in favour of the other PR

**Pull request closed without merging**
