### PR TITLE
Added support for disabling ipv6

### PR DESCRIPTION
**Pull request by dovreshef**
to:
cc: @subspacecommunity/subspace-maintainers
related to:
resolves:

## Background
Add a new environment variable called `SUBSPACE_DISABLE_IPV6`, which is by default 0.
When set to anything but 0, will disable IPV6 support for the tunnel completely.

Reason for the change
Some users have asked for a way to disable IPV6 completely (#117). 
I've also found that with IPV6 enabled, the tunnel DNS forwarding did not work for me on some configuration. Since I do not need IPV6, it was easier to just disable it.

## Testing

Steps for how this change was tested and verified
I've deployed this and verified that it is working.
I do not know how to test this further. But the changes are not so big.

### CODE REVIEW

**Comment by gavinelder** [comment]
I think this doesn't need an extra flag and could just be if ipv6 gateway is not present don't enable ipv6, likewise ipv4, if both are missing then log an error and exit ?

**Comment by dovreshef** [comment]
@gavinelder @jack1902 changed. Please review.

**Comment by skaag** [comment]
> I think this doesn't need an extra flag and could just be if ipv6 gateway is not present don't enable ipv6, likewise ipv4, if both are missing then log an error and exit ?

While you may be right, it does not currently behave the way you describe. And if you disable ipv6 entirely in Ubuntu Focal, subspace won't even start properly.

**Review by skaag — COMMENTED** [review]
Looks legit!

**Review by lupieczonka — APPROVED** [review]

**Review by mike-serchenia — APPROVED** [review]

**Review by lupieczonka — APPROVED** [review]

**Review by agonbar — APPROVED** [review]

**Comment by agonbar** [comment]
@all-contributors please add @dovreshef for code

**Pull request merged**
