### PR TITLE
Support prometheus exporter friendly_json field

### LINKED ISSUE #139: Make use of "friendly name" in wireguard.config
**Is your feature request related to a problem? Please describe.**
I am using [a prometheus exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter) for monitoring traffic stats about my wg clients. Currently all clients are showing up as their public keys. The exporter has a feature to parse comments added to each client section in the wireguard.config to display as their friendly human-readable format [see here](https://github.com/MindFlavor/prometheus_wireguard_exporter#friendly-names).

**Describe the solution you'd like**
Subspace has a client name attribute which shows up in the web UI. Exporting this name in the generation of the wireguard.config as a comment in each client's section would not only be beneficial when using the above linked exporter, but also for any other setup where additional software will somehow interact with the wireguard.config, or at least improve the human readability of the generated config file, wherever it is needed.

### PR DESCRIPTION
**Pull request by gchamon**
to: @subspacecommunity/subspace-maintainers
cc: @subspacecommunity/subspace-maintainers
related to:
resolves: https://github.com/subspacecommunity/subspace/issues/139

## Background

[Prometheus wireguard exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter) allows for friendly names to be exported along with wireguard specific info. This pull request aims to support the comment that enables the exporter to do that, thus making monitoring subspace with Prometheus easier for SecOps teams.

### Changes

* added `# friendly_json` tag to both client and peer configs
* moved `server.conf` generation from `entrypoint.sh` to both routes `/profile/add` and `/profile/delete`
* added `MutexBash` that allows for synchronized bash execution
* to avoid race conditions, the `server.conf` generation is hidden behind `ServerConfig` struct, that uses `MutexBash` to update the server configuration synchronously
* updated the readme with a `docker-compose` example that enables the prometheus exporter

## Testing

- checkout this branch
- use the following `docker-compose.yml`
```yml
version: "3.3"
services:
  subspace:
    image: subspace-local
    build: ./subspace
    container_name: subspace
    volumes:
    - ./subspace-data:/data
    restart: always
    environment:
     - SUBSPACE_HTTP_HOST=localhost
     - SUBSPACE_LETSENCRYPT=false
     - SUBSPACE_HTTP_INSECURE=true
     - SUBSPACE_HTTP_ADDR=":80"
     - SUBSPACE_NAMESERVERS=1.1.1.1,8.8.8.8
     - SUBSPACE_LISTENPORT=51820
     - SUBSPACE_IPV4_POOL=10.99.97.0/24
     - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
     - SUBSPACE_DISABLE_DNS=0
     - SUBSPACE_IPV6_NAT_ENABLED=1
    cap_add:
     - NET_ADMIN
    network_mode: "host"
  prometheus_exporter:
    image: mindflavor/prometheus-wireguard-exporter
    container_name: prometheus_exporter
    volumes:
      - ./subspace-data:/data
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: "-a -n /data/wireguard/server.conf"
```
- `docker-compose build`
- `docker-compose up`
- login to `http://localhost`
- create an admin profile
- `cat ./subspace-data/wireguard/server.conf`. The config file should be update as soon as you create a profile. It should also contain the `friendly_json` tag with the correct values
- create a client profile and test if the `user_type` is correctly set to `client`
- `curl http://localhost:9586/metrics` should display prometheus metrics with the correct key=value pairs from `friendly_json`

## Next steps

- Provide a way to refresh current peer config files

### CODE REVIEW

**Comment by agonbar** [comment]
I've tested this, some things that may not be perfect:

- On the example on the .md, we could keep a smaller docker-compose.yml example, with the minimum required, and the complete one, with the exporter, to avoid confusion.
- The friendly_json is also being created in the clients .conf files, this is not needed for the exporter.
- The permissions on the ./subspace-data/ gave me a lot of problems, the exporter wouldn´t lauch, the docker-compose wouldn´t restart, etc.
- We need to rebase this from master

**Comment by agonbar** [comment]
Ok, the rebase is done, I manually changed the permissions on the folder and tested and the rest works perfectly, so just check the othe points and it will be perfect.

Many thanks for all the contributions!

**Review by agonbar — CHANGES_REQUESTED** [review]
- On the example on the .md, we could keep a smaller docker-compose.yml example, with the minimum required, and the complete one, with the exporter, to avoid confusion.
- The friendly_json is also being created in the clients .conf files, this is not needed for the exporter.
- The permissions on the ./subspace-data/ gave me a lot of problems, the exporter wouldn´t lauch, the docker-compose wouldn´t restart, etc.

**Comment by gchamon** [comment]
>     * On the example on the .md, we could keep a smaller docker-compose.yml example, with the minimum required, and the complete one, with the exporter, to avoid confusion.
> 
>     * The friendly_json is also being created in the clients .conf files, this is not needed for the exporter.
> 
>     * The permissions on the ./subspace-data/ gave me a lot of problems, the exporter wouldn´t lauch, the docker-compose wouldn´t restart, etc.

I wonder if maybe setting the volume map on the exporter for read only would preserve the original permissions from subspace

**Comment by gchamon** [comment]
@agonbar I tested with read only permissions for the exporter and had zero issues. Here is my complete `docker-compose.yml` file:

```yaml
version: "3.3"
services:
  subspace:
    image: subspace-local
    build: ./subspace
    container_name: subspace
    volumes:
      - ./subspace-data:/data
      - ./dnsmasq.d:/etc/dnsmasq.d
    restart: always
    environment:
      - SUBSPACE_HTTP_HOST=192.168.0.4
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_HTTP_INSECURE=true
      - SUBSPACE_HTTP_ADDR=":80"
      - SUBSPACE_NAMESERVERS=1.1.1.1,8.8.8.8
      - SUBSPACE_LISTENPORT=51820
      - SUBSPACE_IPV4_POOL=10.99.97.0/24
      - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
      - SUBSPACE_DISABLE_DNS=0
      - SUBSPACE_IPV6_NAT_ENABLED=1
    cap_add:
      - NET_ADMIN
    network_mode: "host"
  prometheus_exporter:
    image: mindflavor/prometheus-wireguard-exporter
    container_name: prometheus_exporter
    volumes:
      - ./subspace-data:/data:ro
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: "-a -n /data/wireguard/server.conf"
```
Can you help me replicate your issue?

---

Also, regarding the readme. I am not sure what I am supposed to change. Should I make the example with the prometheus exporter shorter?

**Comment by gchamon** [comment]
@agonbar another thing that came to mind. If you are upgrading a running subspace server, newer client configs will be populated with the `friendly_json` field, but older ones will lack it. We should think of a routine to migrate older configs to newer configs.

However, this behaviour is not exclusive to this PR. Any changes made to the server config will not reflect in the already created client configs.

I think this warrants an issue of its own. Do you also share this POV?

**Comment by gchamon** [comment]
- [ ] On the example on the .md, we could keep a smaller docker-compose.yml example, with the minimum required, and the complete one, with the exporter, to avoid confusion.
- [ ] The friendly_json is also being created in the clients .conf files, this is not needed for the exporter.
- [ ] The permissions on the ./subspace-data/ gave me a lot of problems, the exporter wouldn´t lauch, the docker-compose wouldn´t restart, etc.

**Comment by gchamon** [comment]
Fixed a problem with updating from a long running subspace service. Updating would cause server.conf to be recreated after the wg0 interface is set during startup, causing any peers created before updating to be missed.

To circumvent it, I added the method Sync to the WireguardServerConfig struct that calls `wg syncconf` with the updated server.conf. This will effectively delegate both the recreation of the wireguard config and refresh of the wg0 interface to subspace.

**Pull request closed without merging**
